server.port=9002

# MySQL Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Jackson Configuration
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Performance optimization
spring.threads.virtual.enabled=true

# JWT Configuration
app.jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation12345
app.jwt.expiration=86400000
#server.tomcat.threads.max=10
spring.threads.virtual.enabled=true
